/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newlibsys;

import javax.swing.ButtonGroup;
import javax.swing.JTextField;

/**
 *
 * @author Balaji
 */
public class AddBooks extends javax.swing.JPanel {

    /**
     * Creates new form AddBooks
     */

    String feildNotNum[];
    String feildNotLetter[];
    JTextField fdNotNum[];
    JTextField fdNotLetter[];
   
    public AddBooks() {
        initComponents();
     
        fdNotLetter = new JTextField[2];
        fdNotLetter[0]=book_id;
        fdNotLetter[1]=edition;
        fdNotNum=new JTextField[3];
        fdNotNum[0]=book_name;
        fdNotNum[1]=author;
        fdNotNum[2]=publication;
        feildNotLetter=new String[2];
        feildNotNum=new String[3];
        feildNotLetter=new String[]{"Book ID","Edition"};
        feildNotNum=new String[]{"Book Name","Author","Publication"};
                
        
             
        group = new ButtonGroup();
        books.setSelected(true);
        group.add(books);
        group.add(project);
        group.add(member);
        add.addActionListener(new AddBookAction());
        addMouseListener(new AddBookAction());
    }
    
        

          
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        id_Label = new javax.swing.JLabel();
        name_Label = new javax.swing.JLabel();
        Autho_Label = new javax.swing.JLabel();
        Edition_Label = new javax.swing.JLabel();
        pub_label = new javax.swing.JLabel();
        book_id = new javax.swing.JTextField();
        book_name = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        edition = new javax.swing.JTextField();
        publication = new javax.swing.JTextField();
        aBookLabel = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        member = new javax.swing.JRadioButton();
        project = new javax.swing.JRadioButton();
        books = new javax.swing.JRadioButton();
        message = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        jRadioButton4.setText("jRadioButton1");

        jTextField1.setText("jTextField1");

        id_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        id_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_Label.setText("Book ID");

        name_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_Label.setText("Book Name");

        Autho_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Autho_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Autho_Label.setText("Author");

        Edition_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Edition_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edition_Label.setText("Edition");

        pub_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pub_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pub_label.setText("Publication");

        book_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_idActionPerformed(evt);
            }
        });

        edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_idActionPerformed(evt);
            }
        });

        publication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicationActionPerformed(evt);
            }
        });

        aBookLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aBookLabel.setText("Add Books");

        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add.setText("Add");

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("Back");

        member.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        member.setText("Member");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });

        project.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        project.setText("Project");
        project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectActionPerformed(evt);
            }
        });

        books.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        books.setText("Books");

        message.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(aBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(member)
                        .addGap(18, 18, 18)
                        .addComponent(project)
                        .addGap(18, 18, 18)
                        .addComponent(books))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(name_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Autho_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Edition_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pub_label))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(edition)
                                    .addComponent(book_id)
                                    .addComponent(book_name)
                                    .addComponent(publication)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aBookLabel)
                    .addComponent(member)
                    .addComponent(project)
                    .addComponent(books))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_Label)
                    .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_Label)
                    .addComponent(book_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Autho_Label)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edition_Label)
                    .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pub_label)
                    .addComponent(publication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(add)
                    .addComponent(back))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void publicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publicationActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberActionPerformed

    private void projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectActionPerformed
        // TODO add your handling code here:
        new AddBookAction().actionPerformed(evt);
    }//GEN-LAST:event_projectActionPerformed

    private void book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_idActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        book_id.setText("");
        book_name.setText("");
        author.setText("");
        edition.setText("");
        publication.setText("");
        book_id.requestFocusInWindow();
        
       
    }//GEN-LAST:event_clearActionPerformed

    ButtonGroup group;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autho_Label;
    private javax.swing.JLabel Edition_Label;
    private javax.swing.JLabel aBookLabel;
    private javax.swing.JButton add;
    javax.swing.JTextField author;
    javax.swing.JButton back;
    javax.swing.JTextField book_id;
    javax.swing.JTextField book_name;
    javax.swing.JRadioButton books;
    private javax.swing.JButton clear;
    javax.swing.JTextField edition;
    private javax.swing.JLabel id_Label;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    javax.swing.JRadioButton member;
    javax.swing.JLabel message;
    private javax.swing.JLabel name_Label;
    javax.swing.JRadioButton project;
    private javax.swing.JLabel pub_label;
    javax.swing.JTextField publication;
    // End of variables declaration//GEN-END:variables
}
