/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package newlibsys;

import javax.swing.ButtonGroup;

/**
 *
 * @author Balaji
 */
public class BookIssue extends javax.swing.JPanel {

    /**
     * Creates new form BookIssue
     */
 
    public BookIssue() {
        initComponents();
          
        ButtonGroup group =new ButtonGroup();
        book.setSelected(true);
        group.add(book);
        group.add(project);
        issue.addActionListener(new IssueBookAction());
        addMouseListener(new IssueBookAction());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookID_lbl = new javax.swing.JLabel();
        mmbrID_lbl = new javax.swing.JLabel();
        bookID = new javax.swing.JTextField();
        mmbrID = new javax.swing.JTextField();
        issue = new javax.swing.JButton();
        back = new javax.swing.JButton();
        bookIssue_lbl = new javax.swing.JLabel();
        book = new javax.swing.JRadioButton();
        project = new javax.swing.JRadioButton();
        message = new javax.swing.JLabel();

        bookID_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bookID_lbl.setText("Book ID");

        mmbrID_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mmbrID_lbl.setText("Member ID");

        bookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDActionPerformed(evt);
            }
        });

        mmbrID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmbrIDActionPerformed(evt);
            }
        });

        issue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        issue.setText("Issue");

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        bookIssue_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookIssue_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookIssue_lbl.setText("Book Issue");

        book.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        book.setText("Books");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        project.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        project.setText("Projects");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bookIssue_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(book)
                        .addGap(32, 32, 32)
                        .addComponent(project))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mmbrID_lbl)
                                    .addComponent(bookID_lbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mmbrID)
                                    .addComponent(bookID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookIssue_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book)
                    .addComponent(project))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookID_lbl)
                    .addComponent(bookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmbrID_lbl)
                    .addComponent(mmbrID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookActionPerformed

    private void mmbrIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmbrIDActionPerformed
        // TODO add your handling code here:
        new IssueBookAction().actionPerformed(evt);
    }//GEN-LAST:event_mmbrIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton back;
    javax.swing.JRadioButton book;
    javax.swing.JTextField bookID;
    private javax.swing.JLabel bookID_lbl;
    private javax.swing.JLabel bookIssue_lbl;
    private javax.swing.JButton issue;
    javax.swing.JLabel message;
    javax.swing.JTextField mmbrID;
    private javax.swing.JLabel mmbrID_lbl;
    javax.swing.JRadioButton project;
    // End of variables declaration//GEN-END:variables
}
