/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package newlibsys;

import javax.swing.ButtonGroup;

/**
 *
 * @author Balaji
 */
public class BookReturn extends javax.swing.JPanel {

    /**
     * Creates new form BookIssue
     */
    
    public BookReturn() {
        
        initComponents();
        
        ButtonGroup group =new ButtonGroup();
        book.setSelected(true);
        group.add(book);
        group.add(project);
        return_bt.addActionListener(new ReturnBookAction());
        addMouseListener(new ReturnBookAction());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mmbrID_lbl = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        return_bt = new javax.swing.JButton();
        back = new javax.swing.JButton();
        bookReturn_lbl = new javax.swing.JLabel();
        book = new javax.swing.JRadioButton();
        project = new javax.swing.JRadioButton();
        message = new javax.swing.JLabel();

        mmbrID_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mmbrID_lbl.setText("Book ID");

        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });

        return_bt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        return_bt.setText("Return");
        return_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("Back");

        bookReturn_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookReturn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookReturn_lbl.setText("Book Return");

        book.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        book.setText("Books");

        project.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        project.setText("Projects");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(return_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(bookReturn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(project))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mmbrID_lbl)
                                .addGap(27, 27, 27)
                                .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bookReturn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book)
                    .addComponent(project))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmbrID_lbl)
                    .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(return_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void return_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_return_btActionPerformed

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
        new ReturnBookAction().actionPerformed(evt);
    }//GEN-LAST:event_bookidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton back;
    javax.swing.JRadioButton book;
    private javax.swing.JLabel bookReturn_lbl;
    javax.swing.JTextField bookid;
    javax.swing.JLabel message;
    private javax.swing.JLabel mmbrID_lbl;
    javax.swing.JRadioButton project;
    private javax.swing.JButton return_bt;
    // End of variables declaration//GEN-END:variables
}
